### ISSUE TITLE
eventmachine not initialized: evma_send_data_to_connection (RuntimeError)

### ISSUE THREAD

**Issue by leomayleomay** [ezmobius/nanite#8]
System configurations:
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]
amqp (0.6.0)
eventmachine (0.12.10)
rabbitmq 1.7.0
erlang 5.6.5

I follow the steps given by the "Test Nanite (finally)", 

First, I created a new agent called bob, http://gist.github.com/223056

Second, I created a new mapper in another shell, http://gist.github.com/223058

**Comment by roidrage** [comment]
Could you please install EventMachine 0.12.8 and check if that works? I'd be curious if the problem is the just recently released 0.12.10 which we haven't tried with Nanite and the AMQP library yet.

**Comment by leomayleomay** [comment]
thank you, it works

**Comment by roidrage** [comment]
Pretty odd that it'd break with a patch release of EventMachine. Thanks for testing, I'll look into it.

**Comment by roidrage** [comment]
The solution is to use the latest AMQP (version 0.6.5) gem, it's up on gemcutter and removes a custom patch for EventMachine. I'll update the documentation accordingly.

**Comment by leomayleomay** [comment]
great info, thank you, mattmatt

**Comment by roidrage** [comment]
Fixed.

**Comment by leomayleomay** [comment]
mattmatt, the problem is still there, environment:
amqp 0.6.5
eventmachine 0.12.10
nanite 0.4.1.13

**Comment by leomayleomay** [comment]
mattmatt, since I switch my mod_rails to conservative spawning mode, it works quite well right now, but you know, I still want it work under smart mode if it's possible

**Comment by roidrage** [comment]
Interesting, though in any way I usually recommend running mappers as separate processes anyway. Reduces that kind of pain quite considerably.

**Comment by leomayleomay** [comment]
mattmatt, for now, I've extracted Nanite related code out of Rails stack, and running it on a DRB server (basically, a separate process), it's working now. Thanks for the tips.
